Batch member addition
crkn-rcdr/Access-Platform pull request #234
Opened 2021-08-11 14:20 UTC by DivyaKrishnan26

Notes:
I have marked my doubts in the files as comments. You might not want to review the svelte files yet. Its just the scaffolding stuff to get the structure away.

2021-08-11 15:09 UTC, SaschaAdler requested changes
If you'd like, I could help you write a test case that covers what the collection member check needs to do.

2021-08-11 15:09 UTC, SaschaAdler commented on packages/couch-utils/src/handlers/access.ts
> +    /*Return the Collection Object here? after forceUpdate?*/
The Collection is retrieved again and returned at the end of this method.

2021-08-11 15:09 UTC, SaschaAdler commented on packages/couch-utils/src/handlers/access.ts
> +      });
This needs to be fleshed out a bit. It's the members that you've filtered that need to have `forceUpdate` run on them.

2021-08-11 15:14 UTC, DivyaKrishnan26 commented on packages/couch-utils/package.json
> +    "lodash.xorwith": "^4.5.0",
Deleted the other lodash and types

2021-08-11 15:15 UTC, DivyaKrishnan26 commented on packages/couch-utils/src/handlers/access.ts
> +  }
So we would want to call the update function here, makes clear

2021-08-11 15:16 UTC, DivyaKrishnan26 commented
Yeah, It would be good to know what the collection member checks need to be done exactly.

2021-08-11 15:19 UTC, DivyaKrishnan26 commented on packages/couch-utils/src/handlers/access.ts
> +      });
Which means this goes in like 
await this.update ({ 
id:args.id,
filteredmembers may be?
})

2021-08-11 16:09 UTC, DivyaKrishnan26 commented on packages/couch-utils/src/handlers/access.ts
> +  }
Doesn't the update method calls the DatabaseHandler method?

2021-08-11 16:13 UTC, SaschaAdler commented on packages/couch-utils/src/handlers/access.ts
> +  }
There's no DatabaseHandler `forceUpdate` method.

You can call the DatabaseHandler `update` method to call the `forceUpdate` update function in Couch. It should look like

```ts
this.update({
  ddoc: "access",
  name: "forceUpdate",
  docId: id
})
```

This `forceUpdate` method doesn't need a `User` passed in, either, so it can just have the signature

```ts
async forceUpdate(id: Noid): Promise<void> {
  ...
}
```

2021-08-11 16:14 UTC, SaschaAdler commented on packages/couch-utils/src/handlers/access.ts
> +      });
For each member in `filteredMembers`, you'll need to call `this.forceUpdate`.

2021-08-11 16:16 UTC, SaschaAdler commented on packages/couch-utils/src/handlers/access.ts
> +      });
Oh, shoot. You also need to do this after `editObject` gets called below, since otherwise Hammer might not pick up on the changes.

2021-08-11 16:54 UTC, SaschaAdler commented
I've merged main into the branch (a couple times, apparently), and added a test case that currently fails, but will succeed when members are updated.

Use `pnpm watch packages` to watch the test output. You might need to wait a minute or two for all the tests to run first.

2021-08-11 18:54 UTC, DivyaKrishnan26 commented on packages/couch-utils/src/handlers/access.ts
> +  }
Should there be any return type for the Promise? Like if the members should be returned here?

2021-08-11 18:56 UTC, DivyaKrishnan26 commented on packages/couch-utils/src/handlers/access.ts
> +      });
The forceUpdate method take in just the Id and the Promise right? So call the forceUpdate(id) for each of the filteredMembers ?

2021-08-11 19:00 UTC, DivyaKrishnan26 commented on packages/couch-utils/src/handlers/access.ts
> +      });
Just trying to figure out how the forceUpdate should be called or each filteredMembers based on the function decleration.

2021-08-11 19:25 UTC, SaschaAdler commented on packages/couch-utils/src/handlers/access.ts
> +      });
forceUpdate just takes an id (the Promise bit in the type declaration is there because it's an `async` function). You'll need to call it for each member's `id`.

2021-08-11 19:28 UTC, SaschaAdler commented on packages/couch-utils/src/handlers/access.ts
> +  }
A function that returns nothing has a return type (i.e. what goes after the colon) of `void`. Since this is an asynchronous function, it has a return type of `Promise<void>`. If you remove the `Promise` you should see an error.

`forceUpdate` should be an asynchronous function that returns nothing.

2021-08-13 18:23 UTC, SaschaAdler requested changes

2021-08-13 18:23 UTC, SaschaAdler commented on packages/couch-utils/src/handlers/access.ts
>        console.log("data in accesshandler", filteredMembers);
You'll want to remove this before merging.

2021-08-13 18:23 UTC, SaschaAdler commented on packages/couch-utils/src/handlers/access.ts
>        }
You have an array of members in `filteredMembers`. You're pushing their ids into a different array, and then running `forceUpdate` on each id in that array. Why use two arrays? There's a type in `access-data` called `ObjectList` that can help here.

```ts
let filteredMembers: ObjectList = [];

if (data.members) {
  filteredMembers = xorWith(data.members, currentMembers, isEqual);
}

// await this.editObject

for (const member of filteredMembers) {
  await this.forceUpdate(member.id);
}

// return, etc.
```

The way you're setting it up, you're running `forceUpdate` on everything twice, which, while it isn't a problem, is unnecessary.

2021-08-13 18:58 UTC, DivyaKrishnan26 commented on packages/couch-utils/src/handlers/access.ts
>        }
I had the other array as Typescript was complaining about assigning values that are of different types. Did not thoroughly know about the ObjectList[], I will make the changes now.

2021-08-20 19:13 UTC, SaschaAdler approved these changes

2021-08-20 19:15 UTC, merged