DMD task: Step 1-3 Lapin routes
crkn-rcdr/Access-Platform pull request #248
Opened 2021-08-13 15:21 UTC by brittnylapierre

### Lapin route: `dmdTask.new`

Input:

```ts
type NewInput = {
  user: User;
  mdType: "csvissueinfo" | "csvdc" | "marc490" | "marcoocihm" | "marcooe";
  file: string;
};
```

Creates a new `dmdtask` document, through a couch-utils method, with an auto-generated uuid, the dmdType, and the file inserted as an attachment. Theoretically, since it's already base64-encoded, the `_attachments` object can be built in the initial request. Will have to research this a little bit. Decoding the string and then uploading it the standard way can work as an alternative.

- [ ] Done

### Lapin route: `dmdTask.get`

Grabs the dmd task by id from the database

- [ ] Done

2021-08-13 18:54 UTC, SaschaAdler commented
We should probably set up type guards for DMDTasks, shouldn't we.

2021-08-13 19:21 UTC, SaschaAdler requested changes
I'm more curious about my comments than requesting that anything is changed, necessarily.

(even though I'm about to click "request changes")

2021-08-13 19:21 UTC, SaschaAdler commented on services/admin/src/lib/components/dmd/DmdTaskTimeInfoTable.svelte
> +  {/if}
Do you need to use `?.` and array-style indexing here? All of these fields are required in the DMDTask schema.

2021-08-13 19:21 UTC, SaschaAdler commented on services/admin/src/routes/dmd/[taskId]/index.svelte
>    {/if}
Same idea here has my other comment. I also wonder how Svelte handles the type guarding you get from using e.g. `WaitingDMDTask.safeParse`?

In regular old TypeScript, I'd do this with

```ts
if (WaitingDMDTask.safeParse(dmdTask).success) {
  // dmdTask is a WaitingDMDTask
} else if (FailedDMDTask.safeParse(dmdTask).success) {
  // dmdTask is a FailedDMDTask
} else {
  // because DMDTask is a union, you can be sure dmdTask is a SucceededDMDTask, even if TypeScript can't
}
```

2021-08-13 20:25 UTC, brittnylapierre commented on services/admin/src/routes/dmd/[taskId]/index.svelte
>    {/if}
Ooo that's much nicer, it looks like it works in the template too! I'll see if it gets rid of the type warnings so I don't need the getters too, thanks for suggesting this

2021-08-13 20:26 UTC, brittnylapierre commented on services/admin/src/lib/components/dmd/DmdTaskTimeInfoTable.svelte
> +  {/if}
@SaschaAdler No i don't think so then! I remember in the last version of the page there were lots of checks like that but if the safeparse from below is enough checking then I'll just use that instead :)

2021-08-13 20:39 UTC, brittnylapierre commented on services/admin/src/lib/components/dmd/DmdTaskTimeInfoTable.svelte
> +  {/if}
@SaschaAdler  When I use dot notation, I do get some complaints for some of the properties, like: 
dmdTask.process.message

but I can do: 
dmdTask.process["message"] 

Without any issues, so I'll do that, and I can at least get rid of the ?. too now!

2021-08-13 20:41 UTC, brittnylapierre commented on services/admin/src/routes/dmd/[taskId]/index.svelte
>    {/if}
@SaschaAdler Looks like I still need to cast it if I want to be specific about the types allowed into the state-specific components :(

2021-08-13 20:49 UTC, brittnylapierre commented
> We should probably set up type guards for DMDTasks, shouldn't we.

@SaschaAdler I made some changes based on your above recommendations! I wasn't able to do everything perfectly though.

for the type guards, is that the same thing as isManifest() and isCollection() but for dd task types? I can add that too in this branch if you'd like!

2021-08-16 14:11 UTC, brittnylapierre commented
@SaschaAdler I added the isWaiting... typegaurds in my last commit, based on the ones you made and the safeparse suggestion from above! Let me know if there's any other things you'd like me to change, otherwise I'll merge this and rebase my next PR from main (up next, still working on it: https://github.com/crkn-rcdr/Access-Platform/pull/244) :smile:

2021-08-17 15:46 UTC, SaschaAdler approved these changes

2021-08-17 16:07 UTC, merged