Adding OCR Batch object schemas
crkn-rcdr/Access-Platform pull request #457
Opened 2022-01-17 21:05 UTC by brittnylapierre

I tried to make tests based off of the dmd task tests that were already set up

2022-01-17 21:31 UTC, RussellMcOrmond commented
In this PR, can you create "request", "cancel" and "update" documents for each of the fields?
https://github.com/crkn-rcdr/Access-Platform/tree/main/services/couchdb/dipstaging/design/access/updates
Notice:
https://github.com/crkn-rcdr/Access-Platform/blob/24be76e83434ed6cee4a5de8539b4765[…]ervices/couchdb/dipstaging/design/access/updates/updateSmelt.js

This could be enhanced to not only check it is a string, but that it isn't a blank string.  We could decide that a blank string isn't something we ever want to store.

2022-01-17 21:55 UTC, RussellMcOrmond commented
Ignore what I suggested about the `message` field being optional, and thus blank for a silent success.

I refreshed my memory of https://github.com/crkn-rcdr/Access-Platform/blob/main/packages/data/src/util/ProcessUpdate.ts

Allowing the `message` field to be optional isn't part of a `SucceededProcessResult` or `FailedProcessResult`.

We can leave the spec that way and always have message="" for a silent success.  This would be handled in the _update documents (instead of the delete of the field, have it set field to "").

Whatever is decided, we can do some "spring cleaning" later to have `SmeltProcess` be the same, so it doesn't have to be separate.  Currently it has a unique spec because current code has more fields being optional.

2022-01-17 22:22 UTC, brittnylapierre commented
Ah oops @RussellMcOrmond I ended up making the SucceededProcessResult or FailedProcessResult have optional messages :o And added the tests for those cases. Is that okay too? I can revert that change if you prefer.

2022-01-18 00:44 UTC, brittnylapierre commented
I ended up making a custom process result for the batches that can have no message, we can update the general process result and get rid of the smelt and ocr custom ones some future time

2022-01-18 00:45 UTC, brittnylapierre commented
I made tests in /Access-Platform/packages/couch-utils/src/handlers/ocr.spec.ts to test all the update design docs and they're passing

2022-01-18 13:21 UTC, RussellMcOrmond requested changes

2022-01-18 13:21 UTC, RussellMcOrmond commented on packages/data/src/ocr/Batch.spec.ts
> +const then = timestamp(Date.now() - 100);
The update documents will be using ISO dates, so probably a good double-check to use the same date format for the testing.

2022-01-18 13:21 UTC, RussellMcOrmond commented on packages/data/src/ocr/Batch.spec.ts
> +    processDate: now,
No or blank message on a `succeeded: false` is actually a bug in the microservice, and should never happen.

2022-01-18 13:24 UTC, RussellMcOrmond commented
I saved before finishing.  I added a Queue and status.  While I tested by modifying some of the test documents in the database, you may want to add some additional fixtures and tests for them.  Adjust them as you feel appropriate.

2022-01-18 14:46 UTC, brittnylapierre commented on packages/data/src/ocr/Batch.spec.ts
> +const then = timestamp(Date.now() - 100);
Okay! I've changes them to iso strings

2022-01-18 14:47 UTC, brittnylapierre commented on packages/data/src/ocr/Batch.spec.ts
> +    processDate: now,
Okay! I made it so that the failed versions use the regular failed process update, so messages are required

2022-01-18 14:52 UTC, RussellMcOrmond approved these changes

2022-01-18 14:52 UTC, merged